#!/usr/bin/env python

import os
import hydra
import urllib.request

if hydra.__version__ != "1.3.2":
    raise RuntimeError("different hydra version has been found, cannot patch")

hydra_root = os.path.dirname(hydra.__file__)
utils_path = os.path.join(hydra_root, "core", "utils.py")

urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/gleize/hydra/78f00766b5f37672aa7232ebbf01bdd74246bd60/hydra/core/utils.py",
    utils_path,
)
