"""标准交换格式导出（P4）：OpenSCENARIO 1.2 XML + CommonRoad XML（最小可用）。

**关于地图的诚实说明**：预处理数据（`data/waymo/processed/*`）里**没有 roadgraph/车道**
（要从 raw tfrecord 里抽），所以这两份导出里：
- 车/人的**世界轨迹、尺寸、速度**都是真实且完整的；
- 道路部分是**占位**：OpenSCENARIO 只引用一个 LogicFile 名字并可留空；
  CommonRoad 里放一条由 ego 轨迹拟合的**线性 lanelet 占位路网**，`map_source` 字段标明是占位。
下游要用自己的高精地图时，替换 road/lanelet 段即可；同时我们会额外导出一份
`*.world.json`（世界坐标轨迹，y-up，米），保证信息不丢。

坐标系：重建世界系是 **y-up**（x 右、y 上、z 前）。导出时：
- OpenSCENARIO：直接写世界 x/y/z + 由 yaw 推 h（不额外换轴，文件里注明）；
- CommonRoad：二维平面映射 `X=x, Y=-z`（保持右手系），`yaw_cr = atan2(dY, dX)`。

用法：
    python scenario_export.py --scene <重建场景> --scenario rear-end --out output/export --name demo
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

ROOT = Path(__file__).resolve().parents[2]


# ==================== 轨迹收集 ====================

def collect_tracks(tm, frames: Sequence[int], roles: Optional[Dict[str, int]] = None,
                   ego_track: Optional[int] = None,
                   only_tracks: Optional[Sequence[int]] = None) -> List[Dict[str, Any]]:
    """把 TrackManager 里的（编辑后）轨迹整理成导出用的 track 列表。

    返回 [{"track_id", "role", "dimensions", "poses": {frame: 4x4 list}, "speed_mps"}]
    """
    role_of = {int(v): k for k, v in (roles or {}).items()}
    tids: List[int] = []
    for f in frames:
        try:
            for o in tm.get_frame_objects(int(f)):
                t = int(o["track_id"])
                if t not in tids:
                    tids.append(t)
        except Exception:  # noqa: BLE001
            continue
    out = []
    if only_tracks is not None:
        keep = {int(x) for x in only_tracks}
        tids = [t for t in tids if t in keep]
    for tid in tids:
        poses = {}
        for f in frames:
            p = tm.get_track_pose(tid, int(f))
            if p is not None:
                poses[int(f)] = np.asarray(p, dtype=np.float64).tolist()
        if not poses:
            continue
        fs = sorted(poses.keys())
        spd = 0.0
        if len(fs) >= 2:
            a = np.asarray(poses[fs[-1]], dtype=np.float64)[:3, 3]
            b = np.asarray(poses[fs[0]], dtype=np.float64)[:3, 3]
            spd = float(np.linalg.norm(a - b) / max(0.1, (fs[-1] - fs[0]) / 10.0))
        dims = tm.get_track_dimensions(tid) or [4.5, 2.0, 1.6]
        out.append({"track_id": int(tid),
                    "role": role_of.get(int(tid), "ego" if tid == ego_track else "actor"),
                    "is_ego": bool(ego_track is not None and int(tid) == int(ego_track)),
                    "dimensions": [float(abs(x)) for x in dims[:3]],
                    "poses": poses, "speed_mps": round(spd, 3)})
    return out


def _yaw(pose: np.ndarray) -> float:
    P = np.asarray(pose, dtype=np.float64)
    return math.atan2(float(P[0, 2]), float(P[2, 2]))


# ==================== OpenSCENARIO ====================

def export_openscenario(tracks: List[Dict[str, Any]], out_path: str, dt: float = 0.1,
                        map_file: str = "placeholder.xodr", name: str = "dggt_scenario",
                        author: str = "DGGT studio") -> str:
    """导出 OpenSCENARIO 1.2：每个 track 一条 FollowTrajectory(Polyline) 动作。"""
    root = ET.Element("OpenSCENARIO")
    ET.SubElement(root, "FileHeader", {
        "revMajor": "1", "revMinor": "2", "name": name,
        "version": "1.2", "date": "1970-01-01T00:00:00",
        "description": f"generated by {author}; world frame is y-up (x right, y up, z forward), meters",
        "author": author})
    rn = ET.SubElement(root, "RoadNetwork")
    ET.SubElement(rn, "LogicFile", {"filepath": map_file})
    ents = ET.SubElement(root, "Entities")
    sb = ET.SubElement(root, "Storyboard")
    init = ET.SubElement(sb, "Init")
    acts = ET.SubElement(init, "Actions")
    # 注意：不同 track 的帧集合可能不同 → 每个 track 用自己的首帧做 Init/时间基准

    for t in tracks:
        nm = f"ego" if t["is_ego"] else f"actor_{t['track_id']}"
        veh = ET.SubElement(ents, "ScenarioObject", {"name": nm})
        cat = "vehicle" if max(t["dimensions"]) > 1.2 else "pedestrian"
        v = ET.SubElement(veh, cat if cat == "vehicle" else "Pedestrian", {"name": nm, "mass": "1500" if cat == "vehicle" else "80"})
        bb = ET.SubElement(v, "BoundingBox")
        c = ET.SubElement(bb, "Center", {"x": "0.0", "y": "0.0", "z": str(round(t["dimensions"][1] / 2.0, 3))})
        d = ET.SubElement(bb, "Dimensions", {"width": str(round(t["dimensions"][0], 3)),
                                             "length": str(round(t["dimensions"][2], 3)),
                                             "height": str(round(t["dimensions"][1], 3))})
        # Init：世界坐标起始位姿
        tf0 = min(t["poses"].keys())
        p0 = np.asarray(t["poses"][tf0], dtype=np.float64)
        yaw = _yaw(p0)
        eg = ET.SubElement(acts, "Private", {"entityRef": nm})
        pv = ET.SubElement(eg, "PrivateAction")
        ta = ET.SubElement(pv, "TeleportAction")
        pos = ET.SubElement(ta, "Position")
        ET.SubElement(pos, "WorldPosition", {
            "x": str(round(float(p0[0, 3]), 4)), "y": str(round(float(p0[2, 3]), 4)),
            "z": str(round(float(p0[1, 3]), 4)),
            "h": str(round(yaw, 6)), "p": "0.0", "r": "0.0"})

    story = ET.SubElement(sb, "Story", {"name": "trajectories"})
    act = ET.SubElement(story, "Act", {"name": "main"})
    mg = ET.SubElement(act, "ManeuverGroup", {"maximumExecutionCount": "1", "name": "all"})
    actors_el = ET.SubElement(mg, "Actors", {"selectTriggeringEntities": "false"})
    for t in tracks:
        ET.SubElement(actors_el, "EntityRef",
                      {"entityRef": "ego" if t["is_ego"] else f"actor_{t['track_id']}"})
    man = ET.SubElement(mg, "Maneuver", {"name": "follow"})
    for t in tracks:
        nm = "ego" if t["is_ego"] else f"actor_{t['track_id']}"
        ev = ET.SubElement(man, "Event", {"name": f"follow_{nm}", "priority": "overwrite"})
        ac = ET.SubElement(ev, "Action", {"name": f"follow_{nm}"})
        pa = ET.SubElement(ac, "PrivateAction")
        lt = ET.SubElement(pa, "LongitudinalAction")
        sp = ET.SubElement(lt, "SpeedAction")
        dyn = ET.SubElement(sp, "SpeedActionDynamics", {"dynamicsShape": "step", "value": "0", "dynamicsDimension": "time"})
        sat = ET.SubElement(sp, "SpeedActionTarget")
        ET.SubElement(sat, "AbsoluteTargetSpeed", {"value": str(round(max(0.1, t["speed_mps"]), 3))})
        tele = ET.SubElement(pa, "TeleportAction")
        posn = ET.SubElement(tele, "Position")
        ET.SubElement(posn, "WorldPosition", {"x": "0.0", "y": "0.0", "z": "0.0", "h": "0.0"})
        # 轨迹（Polyline）
        tr = ET.SubElement(pa, "RoutingAction")
        ft = ET.SubElement(tr, "FollowTrajectoryAction")
        traj_el = ET.SubElement(ft, "Trajectory", {"name": f"traj_{nm}", "closed": "false"})
        traj_el.append(_polyline(t["poses"], dt))
        tref = ET.SubElement(ft, "TimeReference")
        ET.SubElement(tref, "Timing", {"domainAbsoluteRelative": "absolute", "offset": "0",
                                       "scale": "1"})
        st_trig = ET.SubElement(ev, "StartTrigger")
        cg_s = ET.SubElement(st_trig, "ConditionGroup")
        cond_s = ET.SubElement(cg_s, "Condition", {"name": "start", "delay": "0",
                                                   "conditionEdge": "rising"})
        bv_s = ET.SubElement(cond_s, "ByValueCondition")
        ET.SubElement(bv_s, "SimulationTimeCondition", {"value": "0", "rule": "greaterThan"})
    stop = ET.SubElement(sb, "StopTrigger")
    cg = ET.SubElement(stop, "ConditionGroup")
    cond = ET.SubElement(cg, "Condition", {"name": "end", "delay": "0", "conditionEdge": "rising"})
    bv = ET.SubElement(cond, "ByValueCondition")
    last = max(max(t["poses"].keys()) for t in tracks)
    first = min(min(t["poses"].keys()) for t in tracks)
    ET.SubElement(bv, "SimulationTimeCondition",
                  {"value": str(round((last - first) * dt, 3)), "rule": "greaterThan"})

    _write_xml(root, out_path)
    return out_path


def _entity_ref_list(names: List[str]) -> ET.Element:
    el = ET.Element("EntityRef")
    for n in names:
        el.append(ET.Element("EntityRef", {"entityRef": n}))
    return el


def _polyline(poses: Dict[int, List[List[float]]], dt: float = 0.1) -> ET.Element:
    pl = ET.Element("Polyline")
    fs = sorted(poses.keys())
    for f in fs:
        P = np.asarray(poses[f], dtype=np.float64)
        ET.SubElement(pl, "Vertex", {
            "time": str(round((f - fs[0]) * dt, 3)),
            "x": str(round(float(P[0, 3]), 4)), "y": str(round(float(P[2, 3]), 4)),
            "z": str(round(float(P[1, 3]), 4)), "h": str(round(_yaw(P), 6))})
    return pl


# ==================== CommonRoad ====================

def export_commonroad(tracks: List[Dict[str, Any]], out_path: str, dt: float = 0.1,
                      name: str = "dggt_scenario", map_source: str = "placeholder (linear lanelet from ego path)",
                      benchmark_id: str = "dggt") -> str:
    """导出 CommonRoad XML（动态障碍 + 一条线性占位 lanelet）。"""
    root = ET.Element("commonRoad", {"commonRoadVersion": "2020a", "benchmarkID": benchmark_id})
    ET.SubElement(root, "author").text = "DGGT studio"
    ET.SubElement(root, "affiliation").text = "studio/backend/scenario_export.py"
    ET.SubElement(root, "source").text = f"reconstructed scene; map_source={map_source}"
    ET.SubElement(root, "timeStepSize").text = str(dt)
    ET.SubElement(root, "date").text = "1970-01-01"

    scen = ET.SubElement(root, "scenario", {"name": name})
    ln = ET.SubElement(scen, "laneletNetwork")
    ln_id = ET.SubElement(ln, "lanelet", {"id": "1"})
    ET.SubElement(ln_id, "leftBound").append(_point_list(_ego_bounds(tracks, 0)))
    ET.SubElement(ln_id, "rightBound").append(_point_list(_ego_bounds(tracks, 1)))
    ET.SubElement(ln_id, "centerLine").append(_point_list(_ego_bounds(tracks, 0.5)))
    pp = ET.SubElement(scen, "planningProblem")
    pp_ini = ET.SubElement(pp, "initialState")
    ET.SubElement(pp_ini, "position", {"x": "0.0", "y": "0.0", "orientation": "0.0"})

    obs_root = ET.SubElement(root, "dynamicObstacles")
    for t in tracks:
        fs = sorted(t["poses"].keys())
        p0 = np.asarray(t["poses"][fs[0]], dtype=np.float64)
        o = ET.SubElement(obs_root, "obstacle", {"id": str(t["track_id"])})
        ET.SubElement(o, "type").text = "pedestrian" if max(t["dimensions"]) <= 1.2 else "car"
        shape_el = ET.SubElement(o, "shape")
        ET.SubElement(shape_el, "rectangle", {"length": str(round(t["dimensions"][2], 3)),
                                              "width": str(round(t["dimensions"][0], 3))})
        ini = ET.SubElement(o, "initialState")
        ET.SubElement(ini, "position", {"x": str(round(float(p0[0, 3]), 4)),
                                        "y": str(round(float(-p0[2, 3]), 4)),
                                        "orientation": str(round(_yaw_cr(p0), 6))})
        ET.SubElement(ini, "velocity").text = str(round(t["speed_mps"], 3))
        ET.SubElement(ini, "orientation", {"exact": str(round(_yaw_cr(p0), 6))})
        traj = ET.SubElement(o, "trajectory")
        for f in fs:
            P = np.asarray(t["poses"][f], dtype=np.float64)
            st = ET.SubElement(traj, "state")
            ET.SubElement(st, "time", {"exact": str(round((f - fs[0]) * dt, 3))})
            ET.SubElement(st, "position", {"x": str(round(float(P[0, 3]), 4)),
                                           "y": str(round(float(-P[2, 3]), 4)),
                                           "orientation": str(round(_yaw_cr(P), 6))})
            ET.SubElement(st, "velocity", {"exact": str(round(t["speed_mps"], 3))})
            ET.SubElement(st, "acceleration", {"exact": "0.0"})
            ET.SubElement(st, "orientation", {"exact": str(round(_yaw_cr(P), 6))})
    _write_xml(root, out_path)
    return out_path


def _yaw_cr(pose: np.ndarray) -> float:
    """CommonRoad 平面：X = x_world, Y = -z_world（保持右手系），yaw 为相对 +X 逆时针。"""
    P = np.asarray(pose, dtype=np.float64)
    fwd = P[:3, 2]
    return math.atan2(-float(fwd[2]), float(fwd[0]))


def _point_list(bounds: List[Tuple[float, float]]) -> ET.Element:
    pl = ET.Element("pointList")
    for x, y in bounds:
        ET.SubElement(pl, "point", {"x": str(round(float(x), 3)), "y": str(round(float(y), 3)), "z": "0.0"})
    return pl


def _ego_bounds(tracks: List[Dict[str, Any]], offset: float) -> List[Tuple[float, float]]:
    """用所有 track 的点云拟合出的"线性占位道路"边界（offset=0/1 左右边界，0.5 中心线）。"""
    pts = []
    for t in tracks:
        for f in sorted(t["poses"].keys()):
            P = np.asarray(t["poses"][f], dtype=np.float64)
            pts.append([float(P[0, 3]), float(P[2, 3])])
    if len(pts) < 2:
        return [(-10.0, 0.0), (10.0, 0.0)]
    A = np.asarray(pts)
    # 主轴方向（PCA）
    c = A.mean(0)
    u, s, vt = np.linalg.svd(A - c, full_matrices=False)
    d = vt[0]
    n = np.array([-d[1], d[0]])
    proj = (A - c) @ d
    lo, hi = float(proj.min()) - 5.0, float(proj.max()) + 5.0
    w = 3.5 if offset != 0.5 else 0.0
    out = []
    for s_ in (lo, hi):
        p = c + d * s_
        out.append((float(p[0] + n[0] * w), float(-(p[1] + n[1] * w))))
    return out


# ==================== 写文件 / 校验 ====================

def _write_xml(root: ET.Element, out_path: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    try:
        ET.indent(root)                     # py>=3.9
    except Exception:  # noqa: BLE001
        pass
    ET.ElementTree(root).write(out_path, encoding="utf-8", xml_declaration=True)


def validate_roundtrip(osc_path: Optional[str], cr_path: Optional[str],
                       tracks: List[Dict[str, Any]], dt: float = 0.1,
                       tol: float = 1e-3) -> Dict[str, Any]:
    """把导出的 XML 解析回来，逐帧对比轨迹（保证"导出的东西没丢/没歪"）。"""
    rep: Dict[str, Any] = {}
    if osc_path and os.path.exists(osc_path):
        root = ET.parse(osc_path).getroot()
        got = {}
        for traj in root.iter("Trajectory"):
            nm = traj.get("name", "")
            pl = traj.find("Polyline")
            pts = []
            for v in (pl.findall("Vertex") if pl is not None else []):
                pts.append((float(v.get("time")), float(v.get("x")), float(v.get("y")), float(v.get("z"))))
            got[nm] = pts
        errs = []
        for t in tracks:
            nm = f"traj_{'ego' if t['is_ego'] else 'actor_' + str(t['track_id'])}"
            fs = sorted(t["poses"].keys())
            exp = [(round((f - fs[0]) * dt, 3), round(float(np.asarray(t['poses'][f])[0, 3]), 4),
                    round(float(np.asarray(t['poses'][f])[2, 3]), 4),
                    round(float(np.asarray(t['poses'][f])[1, 3]), 4)) for f in fs]
            if nm not in got:
                errs.append(f"缺少轨迹 {nm}")
                continue
            if len(got[nm]) != len(exp):
                errs.append(f"{nm} 顶点数 {len(got[nm])} != {len(exp)}")
                continue
            for a, b in zip(got[nm], exp):
                if abs(a[0] - b[0]) > 1e-2 or max(abs(a[1] - b[1]), abs(a[2] - b[2]), abs(a[3] - b[3])) > tol:
                    errs.append(f"{nm} 顶点不一致 {a} vs {b}")
                    break
        rep["openscenario"] = {"ok": not errs, "num_trajectories": len(got), "problems": errs[:5]}
    if cr_path and os.path.exists(cr_path):
        root = ET.parse(cr_path).getroot()
        got = {}
        for ob in root.iter("obstacle"):
            oid = int(ob.get("id"))
            sts = []
            tr = ob.find("trajectory")
            for st in (tr.findall("state") if tr is not None else []):
                pos = st.find("position")
                t_el = st.find("time")
                sts.append((float(t_el.get("exact")), float(pos.get("x")), float(pos.get("y"))))
            got[oid] = sts
        errs = []
        for t in tracks:
            fs = sorted(t["poses"].keys())
            exp = [(round((f - fs[0]) * dt, 3), round(float(np.asarray(t['poses'][f])[0, 3]), 4),
                    round(float(-np.asarray(t['poses'][f])[2, 3]), 4)) for f in fs]
            if t["track_id"] not in got:
                errs.append(f"缺少障碍 {t['track_id']}")
                continue
            if len(got[t["track_id"]]) != len(exp):
                errs.append(f"obstacle {t['track_id']} 状态数 {len(got[t['track_id']])} != {len(exp)}")
                continue
            for a, b in zip(got[t["track_id"]], exp):
                if abs(a[0] - b[0]) > 1e-2 or max(abs(a[1] - b[1]), abs(a[2] - b[2])) > tol:
                    errs.append(f"obstacle {t['track_id']} 状态不一致 {a} vs {b}")
                    break
        rep["commonroad"] = {"ok": not errs, "num_obstacles": len(got), "problems": errs[:5]}
    rep["ok"] = all(v.get("ok") for v in rep.values())
    return rep


def export_world_json(tracks: List[Dict[str, Any]], out_path: str, dt: float = 0.1) -> str:
    """额外导出一份世界坐标轨迹（y-up, 米）——换地图/换工具时信息不丢。"""
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    payload = {
        "frame": {"convention": "world y-up (x right, y up, z forward), meters",
                  "dt": dt, "note": "yaw = atan2(R[0,2], R[2,2]) about +y"},
        "tracks": [{"track_id": t["track_id"], "role": t["role"], "is_ego": t["is_ego"],
                    "dimensions_lwh": [t["dimensions"][2], t["dimensions"][0], t["dimensions"][1]],
                    "speed_mps": t["speed_mps"],
                    "poses": {str(f): t["poses"][f] for f in sorted(t["poses"].keys())}}
                   for t in tracks],
    }
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    return out_path


def main():
    ap = argparse.ArgumentParser(description="导出 OpenSCENARIO / CommonRoad（最小可用）")
    ap.add_argument("--scene", required=True, help="重建场景目录")
    ap.add_argument("--scenario", default="rear-end")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--start", type=int, default=0)
    ap.add_argument("--frames", type=int, default=20)
    ap.add_argument("--fps", type=float, default=10.0)
    ap.add_argument("--out", default="", help="输出目录（默认 <repo>/output/export）")
    ap.add_argument("--name", default="")
    ap.add_argument("--all_tracks", action="store_true",
                    help="导出场景里所有物体（默认只导出 ego + 事故参与者 + 合成参与者）")
    args = ap.parse_args()

    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from dggt_engine import DGGTRenderer
    from track_manager import TrackManager
    import scene_graph
    import corner_case

    renderer = DGGTRenderer(scene_path=args.scene, device="cuda", load_sky=True, verbose=False)
    tm = TrackManager(renderer)
    g = scene_graph.SceneGraph(tm, fps=args.fps)
    g.build(frame_idx=args.start, window=10)
    cands = g.propose_participants(args.scenario, max_candidates=2)
    if not cands:
        raise SystemExit(f"{args.scenario} 没有候选参与者")
    res = corner_case.generate(tm, args.scenario, cands[0], args.start, args.frames,
                              enable_physics=True, fps=args.fps, sampling_seed=args.seed)
    frames = list(range(args.start, args.start + args.frames + 1))
    ego_tid = tm.ego_track_id
    keep = None if args.all_tracks else (
        [ego_tid] if ego_tid is not None else []) + \
        [int(x) for x in (res.get("affected_tracks") or [])] + \
        [int(x) for x in (res.get("synthesized_tracks") or [])]
    tracks = collect_tracks(tm, frames, roles=(res.get("roles") or cands[0]),
                            ego_track=ego_tid, only_tracks=keep)
    name = args.name or f"{args.scenario}_s{args.seed}"
    out_dir = args.out or str(ROOT / "output" / "export" / name)
    osc = export_openscenario(tracks, os.path.join(out_dir, f"{name}.xosc"), dt=1.0 / args.fps, name=name)
    cr = export_commonroad(tracks, os.path.join(out_dir, f"{name}.cr.xml"), dt=1.0 / args.fps, name=name)
    wj = export_world_json(tracks, os.path.join(out_dir, f"{name}.world.json"), dt=1.0 / args.fps)
    rep = validate_roundtrip(osc, cr, tracks, dt=1.0 / args.fps)
    print(json.dumps({"name": name, "num_tracks": len(tracks), "files": [osc, cr, wj],
                      "validation": rep}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
